<?php

namespace CreativeWork\FilamentExact\Endpoints;

use CreativeWork\FilamentExact\Traits\Downloadable;
use CreativeWork\FilamentExact\Traits\Findable;
use CreativeWork\FilamentExact\Traits\Storable;

class Item extends Model
{
    use Downloadable;
    use Findable;
    use Storable;

    protected $fillable = [
        'ID',
        'AverageCost',
        'Barcode',
        'Class_01',
        'Class_02',
        'Class_03',
        'Class_04',
        'Class_05',
        'Class_06',
        'Class_07',
        'Class_08',
        'Class_09',
        'Class_10',
        'Code',
        'CopyRemarks',
        'CostPriceCurrency',
        'CostPriceNew',
        'CostPriceStandard',
        'Created',
        'Creator',
        'CreatorFullName',
        'CustomField',
        'Description',
        'Division',
        'EndDate',
        'ExtraDescription',
        'FreeBoolField_01',
        'FreeBoolField_02',
        'FreeBoolField_03',
        'FreeBoolField_04',
        'FreeBoolField_05',
        'FreeDateField_01',
        'FreeDateField_02',
        'FreeDateField_03',
        'FreeDateField_04',
        'FreeDateField_05',
        'FreeNumberField_01',
        'FreeNumberField_02',
        'FreeNumberField_03',
        'FreeNumberField_04',
        'FreeNumberField_05',
        'FreeNumberField_06',
        'FreeNumberField_07',
        'FreeNumberField_08',
        'FreeTextField_01',
        'FreeTextField_02',
        'FreeTextField_03',
        'FreeTextField_04',
        'FreeTextField_05',
        'FreeTextField_06',
        'FreeTextField_07',
        'FreeTextField_08',
        'FreeTextField_09',
        'FreeTextField_10',
        'GLCosts',
        'GLCostsCode',
        'GLCostsDescription',
        'GLRevenue',
        'GLRevenueCode',
        'GLRevenueDescription',
        'GLStock',
        'GLStockCode',
        'GLStockDescription',
        'GrossWeight',
        'IsBatchItem',
        'IsFractionAllowedItem',
        'IsMakeItem',
        'IsNewContract',
        'IsOnDemandItem',
        'IsPackageItem',
        'IsPurchaseItem',
        'IsSalesItem',
        'IsSerialItem',
        'IsStockItem',
        'IsSubcontractedItem',
        'IsTaxableItem',
        'IsTime',
        'IsWebshopItem',
        'ItemGroup',
        'ItemGroupCode',
        'ItemGroupDescription',
        'Modified',
        'Modifier',
        'ModifierFullName',
        'NetWeight',
        'NetWeightUnit',
        'Notes',
        'Picture',
        'PictureName',
        'PictureThumbnailUrl',
        'PictureUrl',
        'SalesVatCode',
        'SalesVatCodeDescription',
        'SearchCode',
        'SecurityLevel',
        'StandardSalesPrice',
        'StartDate',
        'StatisticalCode',
        'StatisticalNetWeight',
        'StatisticalUnits',
        'StatisticalValue',
        'Stock',
        'Unit',
        'UnitDescription',
        'UnitType',
    ];

    protected $url = 'logistics/Items';

    public function getDownloadUrl(): string
    {
        return $this->PictureUrl;
    }
}
